### ISSUE TITLE
Fähigkeiten Stacks per Fight

### ISSUE THREAD

**Issue by 13Balu02** [DeadlyBossMods/DBM-Retail#632]
Hallo, wollte fragen ob es möglich ist, den Zähler so umzuändern das er nicht in jeder Phase wieder bei (1) anfängt zu zählen, bei diversen Fähigkeiten.

mfg Balu

**Comment by MysticalOS** [comment]
this depends on fight. in many cases resetting count is done for specific reasons (such as timers being sequenced very specifically taht way such as fatescribe, sylvanas, etc.

**Comment by 13Balu02** [comment]
ja zb. sylvanas ? kann man die zähler so ändern das er nicht jede phase neu anfängt zu zählen?

**Comment by MysticalOS** [comment]
What spell comes to mind for sylvanas, for most part each stage has different abilities anyways so even abilities she uses in stage 1 and 3, by time 3 come around reset is fine because it still new rotation.

her abilities specifically reset because of how she's scripted. However, i'm not against supporting non resetting count for abilities it make sense. What abilities you want count continue? I could store reset and non reset counts at same time and add bool for which is displayed in timer (and still use resetting ones for the timer sequence)
