### ISSUE TITLE
Blastenheimer 5000 timer way out

### ISSUE THREAD

**Issue by AtomicElectron** [DeadlyBossMods/DBM-Retail#685]
When using Blastenheimer 5000 Ultra cannon at the Dark Moon Faire and releasing wings at 1 you end up overshooting target.
I tested this a few time releasing between 3 & 2 count gets you a bullseye. I would say 2 1/2 roughly. I have noticed this has been out since they changed the way the Cannon works several patches ago.

**Comment by MysticalOS** [comment]
That's just a buff timer for wings themself, it not for saying when to release. Although, it can be used for that for those that figure out right timing to do so, like you have with the 2.5, then I gguess it's kinda useful.

At one point I tried to make it a bulls eye timer but found that physics didn't actually match between different races or even game versions when they tweak physics of momentum. I recall at one point I did have an alert saying when to release but it was only accurate for some people. Ultimately i scrapped that notion and just let people find out their own magic timing off the debuff timer.

 I actually thought I removed that timer but I guess I forgot after answering https://github.com/DeadlyBossMods/DBM-Retail/issues/158

Instead of deleting it though I'll continue to leave it as is and just answer this question once a year when it comes up :)
