### ISSUE TITLE
Language selection options or better german translation

### ISSUE THREAD

**Issue by ars4l4n** [DeadlyBossMods/DBM-Retail#720]
**Is your feature request related to a problem? Please describe.**
It doesn't feel good to play with some of those announcements in the german DBM translation. Eg in Castle Nathria there's a boss where DBM says: "[Name of Spell] - Move to: Out line of sight" rather than "Move out of line of sight" 

**Describe the solution you'd like**
cleaner translation or a way to change the language to english despite having set the game set to german.

**Describe alternatives you've considered**
Watching boss-guide videos but I feel like DBM mitigates a gameplay issue that WoW has where it doesn't properly introduce you to a bosses' mechanics step by step so that you learn them as you go or use more intuitively understandable mechanics but instead creates the chore of looking up these mechanics for each boss. I've considered BigWigs but heard that it's less explanatory regarding what you have to do during each mechanic.

**Comment by MysticalOS** [comment]
It's very tricky because MoveTo warnings are a template used across a lot of warnings such as

move to playername
move to pylon
move to north

etc

out of line of sight is a niche case that may not be grammatically correct but I'm not sure it also makes sense to create yet another object type JUST for the occasional grammatically incorrect warning. removing "to" on existing object is also out as then the other examples given would be really bad (move playername).

So i'm inclined to decline this for moment
