### ISSUE TITLE
[Retail] Option for DBM to trigger pulltimer audio from /coundown

### ISSUE THREAD

**Issue by TreizeEU** [DeadlyBossMods/DBM-Retail#759]
Are there any way for DBM to trigger its pull-timer audio from when the raidleader uses the /countdown command, just like it does with the /pull and /dbm pull commands?

**Comment by MysticalOS** [comment]
That will not be supported until blizzard improves api to include sender, for security reasons. it's intentionally not supported at this time because api has too many issues.
1. Doesn't include sender
2. isn't supported in classic
3. doesn't let tank use it in group finder (only group leader, which isn't always the tank).

Blizzard has gotten this feedback from us already, they just don't care, and sine they don't care, we can't do anything with it yet.
