### ISSUE TITLE
DBM is not working

### ISSUE THREAD

**Issue by LarionR** [DeadlyBossMods/DBM-Retail#847]
**Describe the bug**

Since DF has started DBM still not working in any dungeons (or raids, or world bosses).
I have already been using it since BfA, no problems were found.
But after DF, after everyday checking up-to-date version the problem still exsist.
Reinstallation didnt help.
Not only my problem but my mates also. Is there any regional blocks or smth else?

**Comment by MysticalOS** [comment]
Installing DBM core installs raids and world bosses, granted this week the world boss mod didn't work due to a bug that was fixed late last night.

Dungeons is a separate download and DBM should literally be spamming you to death the mods aren't missing. I'm even thinking about going as far as making this an intrusive popup that requires typing in a specific phrase to clear just to get the message out that DBM - Dungeons is a separate mod pack that must be installed for dungeon content. I suspect you're missing this module. A lot still are.

**Comment by LarionR** [comment]
Confirmed. Works. Thanks. Probably I missed it in the description.
