### ISSUE TITLE
LUA ERROR SCRIPT TOO LONG (UNDERROOT)

### ISSUE THREAD

**Issue by davidrm15** [DeadlyBossMods/DBM-Retail#898]
Hi! i have this error recently

Message: Interface/AddOns/DBM-Core/DBM-Core.lua:6025: script ran too long
Time: Sun May 21 21:56:02 2023
Count: 1
Stack: Interface/AddOns/DBM-Core/DBM-Core.lua:6025: script ran too long
[string "=[C]"]: ?
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:6025: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:6002>
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:6034: in function `PlaySoundFile'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:9437: in function `Play'
[string "@Interface/AddOns/DBM-Party-BfA/TheUnderrot/UnderrotTrash.lua"]:92: in function `handler'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:976: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:963>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:976: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:963>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by MysticalOS** [comment]
Nothing I can do about this. this is caused by having slow disk access on computer. blizzard has even said not much can do about it either. PlaySoundFile fails if seek time to load sound file takes longer than 200ms. some suggestions include not using a platter based HDD, use SSD only. in. fact wow min spec is an SSD now and runs like crap from HDDs now. another thing is to make sure things like virus can software aren't playing man in middle with file access and causing file access slowdown.
