### ISSUE TITLE
Question: Is the Ready Check/LFG audio re-direct to Master/Dialog using the client's volume?

### ISSUE THREAD

**Issue by TheCheat54** [DeadlyBossMods/DBM-Retail#938]
I'm not certain if this is a bug or not which is why it's more about asking the question. I want to ask specifically about this feature:
![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/60072292/b22b826e-c92a-4787-b11a-f715d3c58601)

Is this feature using the WoW client's volume settings correctly? The Ready Check/LFG Ready sound effect absolutely blows my speakers out when it plays while I have this option enabled. For context, I have Windows sound at 30%, WoW master at 25%, WoW sound effects at 30%, WoW ambience and dialog at 35%, and my physical speaker dial at what would be a 5. All of these settings present a normal audio experience in WoW (and other games) with the distinct exception of the mentioned sound effect. When it plays, I can physically feel the air blowing out of my subwoofer because the volume is so high.

For curiosity's sake, I tested flipping the defined DBM sound audio channel between Master and Dialog but the volume of the Ready Check sound remained unbearably high. DBM's own alert sounds by comparison seem to properly obey all volume settings I have in the WoW client.

Is this a bug? Oversight? Something that is a limitation of the LUA API? I really like being able to disable sound effects but hear these alerts...but the volume is simply too high to keep that tenable these days.

**Comment by MysticalOS** [comment]
I have no control over how loud your audio is. all that does is plays it on master audio slider. nothing more. if it blasts out ears it's cause your master is that loud. the reason you don't notice it i guess is because all other channels are also reduced and it's multiplicitive. so for example your dialog or sound effects are your master * second slider. master is no * second slider

so effectively you're dialog is base * .3 * .35 which means if windows volume is for simple math 100. then master is at 30 and dialog is at 10.5, this means sound playing on master is 3x louder than dialog

so short of it, it's your configuration that's problem. By default master is 100% to match your windows volume, and other sliders are fined tuned to be lower as needed. you probably have your speakers literally blasting, then have multiplicitive sliders turned down that balance anything double reduced out but master is too loud.

**Comment by TheCheat54** [comment]
I've had DBM's own sounds on Master ever since the option was added again way back after Cata's pre-patch temporarily broke it during the final throes of ICC. Long story short, it sounds like perhaps DBM's default sounds were created/saved at a lower absolute volume if they're softer than Ready Check's when played on the same channel. I'd expect these to be of the same quality since a few of the ones I'm still using were sourced from WoW originally, but perhaps something was changed along the way.

If you Google search this issue you'll see that I'm not alone, so there is clearly something but it doesn't sound like LUA grants any control. Thanks for the explanation at least.
